### ISSUE TITLE
Evaluating on "" and None in services_nlp.py

### ISSUE THREAD

**Issue by simon-tarr** [Health-Informatics-UoN/Carrot-Mapper#170]
In `services_nlp.py`when evaluating `pass_from_source=True` we check for a literal blank string (i.e. ""). For example on Line 117:

```
field_text = field.description_column if field.description_column is not "" else field.name
```

Whereas if `pass_from_source=False` (i.e. running at the value level) then we evaluate on `None`. For example on Line 159:

```
field_text = item.scan_report_field.description_column if item.scan_report_field.description_column is not None else item.scan_report_field.name
```

This is due to how Vas' Azure Function reads in data from the scan report. For fields, there is a `field_description` column; this could be blank or contain a descriptive string of text. At the moment, Vas' code casts `field_description` to string (`str(field_description)`) which causes literal blank strings when processing each row (if there is no text in the field_description cell in the scan report). There are no fields in the scan report for value descriptions and therefore explictly set as `None` in her code.

We may want to decide at a later date whether we want to evaluate on "" or None (rather than using both as in the current implementation)

**Comment by AndyRae** [comment]
NLP has been largely removed, so closing this.
