### ISSUE TITLE
Death Table

### ISSUE THREAD

**Issue by calmacx** [Health-Informatics-UoN/Carrot-Mapper#518]
hi all,

Not sure if it's been propagated to who ever is managing this now but as well the specimen table needing fixing the death table is now needed (implemented in CaRROT-CDM here https://github.com/HDRUK/CaRROT-CDM/pull/153 )

**Comment by spco** [comment]
Still me. Is the death table any simpler, or will it require a similar treatment to specimen?

**Comment by calmacx** [comment]
:) should be very straight forward for death, there's not a lot to it:
https://github.com/HDRUK/CaRROT-CDM/blob/c4867cc03761001925276f599b116a1acae71ea6/carrot/cdm/objects/versions/v5_3_1/death.py#L9

We might need some examples of the 'cause' concept ID though - to make sure that returns a domain associated to 'death' and the right names get picked up.

To explain what I mean --- it's the same as how a concept ID for female 8532 has the domain GENDER and then we use a function to look up which table the <domain>_concept_id is in... and pick the first "allowed" table.. in the case of gender - person... I vaguely remember how this all works and might be able to help out, I am still 30% for technical help.

**Comment by spco** [comment]
Now that https://github.com/HDRUK/CaRROT-CDM/pull/153 is merged, are you able to advise on what's required in CaRROT-Mapper to support this @calmacx ?

**Comment by calmacx** [comment]
Yeah sure, do you want to just leave it with me to make a PR or at least a draft PR to show you? I can do it next week

**Comment by spco** [comment]
That would be great, thanks

**Comment by calmacx** [comment]
@spco - this fell off my radar, but will have a stab at it this week

**Comment by spco** [comment]
After discussion, we've decided this is not required for CO-CONNECT. May be required for other projects, but often death is not recorded using the death table, or reasons for death are deduced from observations and conditions around the time of death rather than that column in the death table.

Shelving this for now, but will leave the issue open.

**Comment by AndyRae** [comment]
Closed in favour of #646
