### ISSUE TITLE
View datasets by project

### ISSUE THREAD

**Issue by prquinlan** [Health-Informatics-UoN/Carrot-Mapper#607]
Could it be possible to group datasets by project, it can be hard to find all the connected datasets. It would be great to have a "Alleviate" view for example. 

### Breakdown

This requires 2 new pages; a list of all projects, and a Project detail view - that shows the datasets attached to it.

For the backend, there is an existing list all projects API, but this would require adding Projects to the `DatasetAndDataPartnerListView` serialising, and filtering.

For the frontend - this needs more fetching code for the Projects list, but then 2 new `/projects` + `/projects/[id]` pages.

**Comment by spco** [comment]
This is in the previous backlog, but never been a priority until now - no real blockers.
