### ISSUE TITLE
Delete scan reports after upload

### ISSUE THREAD

**Issue by prquinlan** [Health-Informatics-UoN/Carrot-Mapper#610]
Is there any reason to store the raw scan report after upload? Could we delete them to stop holding on to data unnecessarily? 

# Tasks

- [x] #729
- [x] #730

**Comment by spco** [comment]
This is stored (along with the Data Dictionary file) for later download by the user via the "Download Scan Report File" button. This was introduced as a convenience for checking which file had been used etc.

**Comment by spco** [comment]
After discussion, we've decided this should be an option for the Owner of a Scan Report - they should be able to hard delete a Scan Report, including its associated files.
