### ISSUE TITLE
Reuse of multiple Concept ID's for the ScanReport(SR) Field and ScanReport(SR) Value.

### ISSUE THREAD

**Issue by armando-mv** [Health-Informatics-UoN/Carrot-Mapper#626]
If a SRField or SRValue is mapped to multiple Concept ID's, the reuse process when uploading a new SR only adds one of those multiple Concept ID's to the given Field/Value.

e.g

These are the Concept ID's added to the same SRValue
<img width="2108" alt="Screenshot 2024-01-16 at 16 04 43" src="https://github.com/HDRUK/CaRROT-Mapper/assets/82170942/14584204-f623-4db8-abdb-ce15b42c5c87">

Once is reuploaded, it only CaRROT only resuses one

<img width="2128" alt="Screenshot 2024-01-16 at 16 03 42" src="https://github.com/HDRUK/CaRROT-Mapper/assets/82170942/84f46a13-2c37-4401-887d-32d88f0ef1a9">

**Comment by spco** [comment]
This is a recognised bug - needs fixing.
