### ISSUE TITLE
Overlapping Vocabularies / Standard Mapping

### ISSUE THREAD

**Issue by DrUrwin** [Health-Informatics-UoN/carrot-mapper#630]
PROBLEM STATEMENT:
==================

There can be problems with vocabularies that share a specific code, an example being:

ICD10:   H05.1 - Chronic inflammatory disorders of orbit (https://athena.ohdsi.org/search-terms/terms/45605601)

OPCS4: H05.1 - Total colectomy and anastomosis of ileum to rectum (https://athena.ohdsi.org/search-terms/terms/44510650)

Alex Waldren-Glenn has done some testing within CARROT on using the H05.1 code for NUH purposes. the approach was:

- Part 1 ([Coding overlap test part 1](https://ccom.azurewebsites.net/scanreports/476/)) - Manually map an example overlapping code H05.1 to both OPCS4 and ICD10.

- Part 2 ([Coding overlap testing part 2](https://ccom.azurewebsites.net/scanreports/478/)) -  Provide a data dictionary with the code as OPCS4 / ICD10 and see if Carrot maps the values correctly.

The outcome of the test was thus - verbatim text from Alex's email:

"So Carrot has auto mapped to two concepts, the R is from my previous mapping reuse and the V is from vocab. It looks like Carrot already has some background info for OPCS4 (I tested this with v8.2 testing with coding type .)
 
NUH coding for OPCS4 doesn’t include the “.” that is in Athena. This means that Carrot can’t pick up those codes in my [v8.2 testing with coding type .](https://ccom.azurewebsites.net/scanreports/480/) or other testing via the V vocab method…
 
My main question is on the vocab mapping. For H05.1 carrot vocab mapping gives the value 44510650, which is the omop concept ID for the OPCS4 code.

The mapping that I had previously done (via providing the standard concept id in the DD) gives 4262950. This is the value of the standard concept in SNOMED that I would expect to use for OMOP. (OPCS4 value -> omop concept id -> Non-standard to Standard map (OMOP) -> concept id for the snomed standard concept)
 
From my understanding we need to use standard concept ids for OMOP, so OPCS4 and ICD10 need to be mapped to the snomed standard concept ids. How does this work in carrot? Would the V vocab lookup values be later mapped to standard concept ids?"

N.B.: I (Esmond) can supply the specifically cited email above as it contains screenshots and thus provides a full & better context for the problem.

**Comment by AndyRae** [comment]
1. Investigate the old rules that are wrong, that are now proliferated to other scan reports. 2. Investigate the non-standard / standard, and source value of creating a ScanReportConcept / Rule. Which values are shown in the UI, and the JSON etc. 
3. Includes #626

**Comment by AndyRae** [comment]
Understand what happens when the vocabulary is left blank inside the data dictionary.
Check the documentation reflects the reality. 
Does the reuse function take into the account the vocabulary ?

**Comment by AndyRae** [comment]
![Image](https://github.com/user-attachments/assets/563740b8-8b62-4edd-b13f-0344d57ff2c6)
