### ISSUE TITLE
Ability to delete mapped Table Person ID and Date Event data attributes

### ISSUE THREAD

**Issue by DrUrwin** [Health-Informatics-UoN/Carrot-Mapper#633]
When assigning Person ID and Event Dates to individual dataset tables, then can be altered, but not deleted, so that they are blank.

Currently I am mapping a dataset with no date events (just a test mapping run through), but have assigned a data attribute to an Event Date in error. I can change the assigned data attribute, but cannot return the Event Date to its original blank state.

https://ccom.azurewebsites.net/scanreports/505/ 

N.B.: the Dataset is restricted and Viewers / Editors / Admins are set only to Phil & Esmond

![Screenshot 2024-02-01 at 17 43 55](https://github.com/Health-Informatics-UoN/CaRROT-Mapper/assets/70956694/2fc52c26-b429-48bd-9ae1-052ff025a653)

**Comment by AndyRae** [comment]
Yes these fields are required by Carrot to create rules, which is mentioned in the [Carrot Data Standard](https://carrot4omop.ac.uk/standards/).

Closing this for now, as we have no plans to change this standard.
