### ISSUE TITLE
DEVICE_EXPOSURE Table - Ability to map devices

### ISSUE THREAD

**Issue by DrUrwin** [Health-Informatics-UoN/Carrot-Mapper#636]
I am currently mapping a dataset with associated physical devices, it could be beneficial to be able to represent such concepts.

Additionally, the UK OHDSI OMOP group is currently talking about 'device' data.

https://ohdsi.github.io/CommonDataModel/cdm54.html#DEVICE_EXPOSURE

**Comment by AndrewThien** [comment]
the field "device_type_concept_id" also need to come back to
