### ISSUE TITLE
Add field from MEASUREMENT table

### ISSUE THREAD

**Issue by jbnuh** [Health-Informatics-UoN/Carrot-Mapper#648]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your proposal related to a problem or functionality gap?

The SDE programme has defined a minimum OMOP data model for Cohort Discovery. Measurement data is included as it is relevant to research in the domain. It would be great if the following field can be included in the capability of CaRROT-Mapper.

### Describe your proposal

Please could you add the value_as_concept_id field from the MEASUREMENT table?

### Are you willing to contribute to developing this feature?

🎨 Yes, I'm keen to be involved in design discussions.

**Comment by AndyRae** [comment]
Similar issues with `value_as_concept_id` with #647

**Comment by AndyRae** [comment]
This is a `float` in the OMOP CDM - so we would need validation to ensure we match type.

At rule generation stage we would validate and override this.
