### ISSUE TITLE
Creating a new Dataset without assigning it to a Project places it in all Projects

### ISSUE THREAD

**Issue by spco** [Health-Informatics-UoN/Carrot-Mapper#651]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Creating a new Dataset without assigning it to a Project places it in all Projects.

### Expected Behavior

The form should show an error and refuse to create the Dataset until at least one Project is created.

### Steps To Reproduce

This was replicated on the dev system below:

<img width="1145" alt="image" src="https://github.com/Health-Informatics-UoN/CaRROT-Mapper/assets/11610738/9b4d687f-784c-46b4-b7e5-8b87b92b820d">

After selecting "Add new Dataset", the Project is added to _all_ Projects (or possibly all the Projects the user is in - I've not been able to very).

<img width="1145" alt="image" src="https://github.com/Health-Informatics-UoN/CaRROT-Mapper/assets/11610738/f53cc066-6246-4480-a8f0-0db967c9472a">

### Environment

```markdown
- OS:
- Other environment details:
```

### Are you willing to contribute to resolve this issue?

🎨 Yes, I'm keen to be involved in design discussions.

**Comment by spco** [comment]
Also to note: on the Dataset Details page, a Dataset can have all of its Projects removed. It then becomes unviewable. This shouldn't be possible - the Dataset Details page should error if attempting to remove the last Project from a Dataset.

**Comment by AndyRae** [comment]
Should be fixed in #736

**Comment by AndyRae** [comment]
Should be fixed in #774
