### ISSUE TITLE
Scan Report requires a fresh upload process, whenever there is an error in the upload process

### ISSUE THREAD

**Issue by erummas** [Health-Informatics-UoN/Carrot-Mapper#676]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently whenever there is an issue uploading the scan report it persists even when the updated file is selected in the 'choose file' section. 

### Expected Behavior

Once the new/updated scan report is selected, the scan report upload should run on the new file and 
a) upload if the scan report & dictionary is correct
b) show new errors (if any)

### Environment

```markdown
- OS:
- Other environment details:
```

### Anything else?

-

### Are you willing to contribute to resolve this issue?

None

**Comment by AndyRae** [comment]
Will be fixed in #736.
