### ISSUE TITLE
Fields with large number of values are not loading

### ISSUE THREAD

**Issue by erummas** [Health-Informatics-UoN/CaRROT-Mapper#677]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently the large scan reports are uploading with no errors, however fields with large number of values show 'loading values' status and then the page stops responding. 

### Expected Behavior

Show all the field values 

### Steps To Reproduce

Scan report # 620
Table : share_gp_data.csv
Field: NewRead

### Environment

```markdown
- OS:
- Other environment details:
```

### Are you willing to contribute to resolve this issue?

None

**Comment by AndyRae** [comment]
Yes I agree - this will have to be enabled by pagination. Good to know we can handle the large reports though.

**Comment by AndyRae** [comment]
Will be fixed by #681
