### ISSUE TITLE
Scan Report Fields

### ISSUE THREAD

**Issue by AndyRae** [Health-Informatics-UoN/CaRROT-Mapper#682]
# Summary

Rewrite this view with Nextjs.

Example: `/scanreports/226/tables/840/fields`

Linked to #681, should be able to mostly reuse the frontend components and code from there.

Frontend Tasks:

- [x] Recreate the existing UI
- [x] Define types in Typescript for what is needed
- [x] Add pagination
- [x] Add filtering
- [x] Add sorting
- [ ] Add the "Add Concept" POST
- [ ] Review

Backend Tasks:

- [ ] New API endpoint
- [x] With pagination, filtering, and sorting
- [ ] Testing 
- [x] Add the URLS to proxy it 
- [ ] Review

**Comment by AndyRae** [comment]
Should also fix #677

**Comment by erummas** [comment]
Hello @AndyRae @AndrewThien , I can see that the new UI is back, however the sorting function on 'value' is not there anymore. Is this intentional?

**Comment by AndyRae** [comment]
Hi @erummas - yes it's disabled for now, as it's potentially one of the areas that causes high demand (and therefore downtime), as the legacy UI didn't have this as a feature.
I am hopeful to be able to bring it back quite soon though, we're just providing a graceful incremental approach right now.
