### ISSUE TITLE
Unable to access the Mapper application

### ISSUE THREAD

**Issue by erummas** [Health-Informatics-UoN/CaRROT-Mapper#700]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://github.com/Health-Informatics-UoN/CaRROT-Mapper/assets/58890026/cc75ec7e-4716-4c57-9937-c7c7b221f713)

Hello, I am getting Application Error whilst accessing the Mapper App. Image shared above. 

### Environment

```markdown
- OS:
- Other environment details:
```

### Are you willing to contribute to resolve this issue?

None

**Comment by spco** [comment]
@erummas should be back up now. Please reopen this ticket if it falls over again, though we believe we've understood and fixed the issue so it won't recur.

**Comment by erummas** [comment]
@spco Thank you, it's working now!

**Comment by erummas** [comment]
Hi @spco I am unable to reopen this issue. I am unable to access the mapper. Sharing image below.
![image](https://github.com/Health-Informatics-UoN/CaRROT-Mapper/assets/58890026/886c8ed7-cd90-4896-85e2-c29ed75aabab)

**Comment by spco** [comment]
Hmm, seems to be working again now. It may have been down for a few minutes while updates were applied - could you confirm whether it was down for a long time or short? Thanks.

**Comment by AndyRae** [comment]
This is odd - but my first thought at the screenshot is this might be concentrated on certain urls of the app, as monitoring doesn't indicate anything.

We had a small config update at 13:31 BST today to prepare future updates, but didn't result in any downtime. 
I'm seeing some very long response times around 15:20 BST, but no downtime reported. Currently everything looks fine and initiating a soft restart seems successful. I'll continue to monitor though.

**Comment by erummas** [comment]
This was close to 4:30-5:00 pm, I would say I tried a few times within a half hour window.
