### ISSUE TITLE
💡 Change wording of SR list view filter box

### ISSUE THREAD

**Issue by spco** [Health-Informatics-UoN/CaRROT-Mapper#707]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe your proposal

Please consider changing the wording in the filter box (currently "Filter by dataset") to more closely fit the true function, which is to filter on the "name" column, not the "dataset" column. I appreciate that this is somewhat confusing on the BE given the naming of fields in the ScanReport model 😆 

### Are you willing to contribute to developing this feature?

None

**Comment by AndyRae** [comment]
Yep this is due to the backend model which has to reflected in the API. But the fix is to be able to override this in the data table component with a prop. Should be straightforward to fix.
