### ISSUE TITLE
💡 Addition of owner/editor field on scan reports page

### ISSUE THREAD

**Issue by erummas** [Health-Informatics-UoN/Carrot-Mapper#715]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe your proposal

Sorry suffering from goldfish memory, don't remember if this was visible in the old mapper view but don't see it in the new version. It would be nice to have this information on the main Scan Report page so we could easily filter SRs we are working on.

### Are you willing to contribute to developing this feature?

None

**Comment by spco** [comment]
If memory serves, this would be new functionality, but I can totally see the benefit for filtering 👍

**Comment by AndyRae** [comment]
Yes filtering on owner/editor field was not available in the previous version.
But the column of "owner/uploaded by" was previously visible in the Scan Report list, and has been removed in the update due to the number of columns.

**Comment by erummas** [comment]
@AndyRae for now even if the column is visible without a filter that would work. If the number of columns is a concern, then we could remove the rules column. It's very easy to access rules just by clicking a scan report.

**Comment by AndyRae** [comment]
@erummas - I now see the value of this column, having taken it away - we are going to bring it back.
