### ISSUE TITLE
🐛 Unable to access scan reports list within a dataset

### ISSUE THREAD

**Issue by erummas** [Health-Informatics-UoN/CaRROT-Mapper#717]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi, in the previous mapper version when we clicked the dataset name it would take us to a page with all scan reports associated with that dataset. Now it does nothing, though the hand cursor appears over it. Is this feature intentionally removed? or will become available in future?

### Expected Behavior

Show the scan reports associated with that particular dataset. 

### Environment

```markdown
- OS:
- Other environment details:
```

### Are you willing to contribute to resolve this issue?

None

**Comment by erummas** [comment]
Hi, I have checked and this directs to the same page as the scan report name. This should be taking us to a list of scan reports uploaded under this dataset. 
Not getting the option to re-open this issue.

**Comment by AndyRae** [comment]
Hi Erum - yes this has been removed. Our view on the various links inside the old scan report table, was that it was a poor UI experience, and didn't meet accessibility requirements (links inside rows). 
We can make it easier to get to the dataset page of Scan Reports, but probably from the Scan Report page itself?
