### ISSUE TITLE
🐛 Unable to access table's fieldview

### ISSUE THREAD

**Issue by erummas** [Health-Informatics-UoN/CaRROT-Mapper#718]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Unable to access the tables within a scan report. Upon click nothing happens.

### Environment

```markdown
- OS:
- Other environment details:
```

### Are you willing to contribute to resolve this issue?

None

**Comment by spco** [comment]
Hi @erummas - can you check again please? It's working for me, but it did take a while after the page load for it to become responsive. May have been a deployment blip.

**Comment by spco** [comment]
Oh, I think you're referring to not being able to move from Table view to Field view? Also broken for me. Looks like a URL issue.

@AndyRae looks like the URL is malformed e.g. `https://ccom.azurewebsites.net/scanreports/623tables/3377/`

**Comment by erummas** [comment]
@spco yes unable to access the fields of the tables, sorry I'll edit the heading to make it more clear.

**Comment by AndrewThien** [comment]
@spco We found the problem and its cause. On the way to fix it now. Thanks!

**Comment by erummas** [comment]
@spco unfortunately, it doesn't take me to Not Found Page. It's alright. I will wait till the fix is applied.

**Comment by AndyRae** [comment]
Fixed in #719
