### ISSUE TITLE
Processing and importing concept_ids for bigger tables is taking a long time

### ISSUE THREAD

**Issue by erummas** [Health-Informatics-UoN/Carrot-Mapper#754]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello, currently for bigger tables with large number of field values I am trying to import concepts_ids for the codes that did not map automatically, however the process is very time consuming as it takes minimum 15 seconds and whilst it's processing I cannot add concept_id for another field so have to wait till it's done. I have not noticed this behaviour in smaller tables of the same scan report and it takes 1-2 seconds, so fairly quicker.

### Steps To Reproduce

[Home](https://ccom.azurewebsites.net/)
 / 

[Scan Reports](https://ccom.azurewebsites.net/scanreports/)
 / 

[SHARE_noGP](https://ccom.azurewebsites.net/scanreports/625/)
 / 

[share_smr01_conditions.csv](https://ccom.azurewebsites.net/scanreports/625/tables/3404/)
 / 

[CONDITIONICD10](https://ccom.azurewebsites.net/scanreports/625/tables/3404/fields/134310/)

### Environment

```markdown
- OS:
- Other environment details:
```

### Are you willing to contribute to resolve this issue?

None

**Comment by AndyRae** [comment]
Hi @erummas  - I can't access that scan report, but this is unsurprising and related to the ability of the tool to handle large tables currently.

As we've been working directly on this, could you check the test instance for whether it works better, for what I think is a very similar Scan Report (it fits the above structure): https://ccom-test.azurewebsites.net/scanreports/232/tables/886/fields/15850/

We're intending to deploy this to production this week if it passes testing.

**Comment by erummas** [comment]
Thanks @AndyRae it's working great on test. Very quick. Can't wait for it to be deployed to prod. Thanks again

**Comment by AndyRae** [comment]
That's great to hear @erummas - we'll aim for a production release tomorrow morning, but leave this issue open until then.

Testament to @AndrewThien + @Dev-Akashili for their work on this.

**Comment by Dev-Akashili** [comment]
Thanks! @erummas 

Thanks for the support! @AndyRae

**Comment by AndyRae** [comment]
We've now deployed this fix.

**Comment by erummas** [comment]
Thank @AndyRae, I can see the difference already. However, there is an unusual behaviour, whenever I add a concept, that record vanishes from the page. I did check the next page to see if it moves there but it doesn't show.

**Comment by erummas** [comment]
The above doesn't happen when I sort the values in an order

**Comment by AndrewThien** [comment]
> Thank you @AndyRae, I can see the difference already. However, there is an unusual behaviour, whenever I add a concept, after updating that record vanishes from the page. I did check the next page to see if it moves there but it doesn't show. 

Thanks for reporting. But sorry, I don't fully understand "that record vanishes from the page" mean. Can you maybe take a screenshot or short video?

**Comment by erummas** [comment]
<img width="924" alt="mapper-1" src="https://github.com/Health-Informatics-UoN/Carrot-Mapper/assets/58890026/f35b0390-5ebb-4ae3-a61f-ba4c93378caf">
<img width="909" alt="mapper-2" src="https://github.com/Health-Informatics-UoN/Carrot-Mapper/assets/58890026/9c04de11-4e2b-4513-ac80-061d9c5e9bdd">
<img width="925" alt="mapper-3" src="https://github.com/Health-Informatics-UoN/Carrot-Mapper/assets/58890026/3b630ff3-f932-4329-bc57-0f2e3a88782f">

**Mapping code R54.X** : You can see from the **Search bar** the code after mapping is not on the page.

**Comment by AndyRae** [comment]
Going to just keep this open until we've deployed the fix to production.
