### ISSUE TITLE
Missing fields when trying to set PersonID and Date Event

### ISSUE THREAD

**Issue by armando-mv** [Health-Informatics-UoN/Carrot-Mapper#763]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Not all the fields appear in the drop-down menu. It is limited to 10, and it is not possible to select more. The Field I want to select is further down the list (it's called EVENT_DT).
The search field does not show them either.

<img width="1317" alt="Screenshot 2024-06-21 at 17 08 36" src="https://github.com/Health-Informatics-UoN/Carrot-Mapper/assets/82170942/fa97c3ad-b065-43e8-a590-8c8680059df2">

The SR I'm working on is:

https://ccom.azurewebsites.net/scanreports/638

and it is a reupload of an existing one (https://ccom.azurewebsites.net/scanreports/565/)

### Environment

```markdown
- OS: macOS using Edge 
- Other environment details:
```

### Are you willing to contribute to resolve this issue?

Yes

**Comment by AndyRae** [comment]
Thanks @armando-mv - we should deploy a fix to this on Monday.
