### ISSUE TITLE
'Meas Value' Domain - Map Concepts to

### ISSUE THREAD

**Issue by DrUrwin** [Health-Informatics-UoN/Carrot-Mapper#769]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your proposal related to a problem or functionality gap?

Rachel Sippy at Cambridge would like to be able to map concepts to the 'Meas Value' domain within Carrot - It is current impossible to do so.

### Describe your proposal

Understand what needs to be expanded within Carrot to support mapping to the 'Meas Domain'

### I'm part of a Project Team

Esmond Urwin

### Are you willing to contribute to developing this feature?

✅ Yes, me or my team intend to do the development.

**Comment by AndyRae** [comment]
Examples would be helpful for us to understand this more effectively @DrUrwin

**Comment by erummas** [comment]
This should merge with the value_as_concept_id feature request.

**Comment by DrUrwin** [comment]
I have an email reply regarding examples for the 'Meas Value' domain:

"Here is a table of some examples of the original field and the concept. In the table, there are two source fields that are represented by two OMOP concepts: "Family history of psychiatric disorders" and "Low serum vitamin D".

Source Data | OMOP Concept Name | OMOP Concept ID
-- | -- | --
Caregiver(s) currently provide assistance | Caregiver(s) currently provide assistance | 45880410
Thyroid disease | Thyroid disease | 45879468
Family history of psychiatric disorders | Psychiatric disorder | 36308213
Family history of psychiatric disorders | Family history of clinical finding | 4167217
Low serum vitamin D | Serum vitamin D measurement | 4152982
Low serum vitamin D | Below threshold level | 4129640

**Comment by rsippy** [comment]
Other examples that are in the 'Meas Value' domain:

Never smoker (45879404)
Decline to answer (36210418)
No (45878245) 
Current smoker (36309332)

**Comment by AndyRae** [comment]
@rsippy - if you have a sample Scan Report that would helpful for our team to implement this
