### ISSUE TITLE
Mapping reuse feature forcing the automated mapping to map to incorrect concept_id

### ISSUE THREAD

**Issue by erummas** [Health-Informatics-UoN/Carrot-Mapper#778]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am observing that mapper is generating incorrect automated mappings (V) OPCS4 codes that have reused concepts from previous scan report(s) 
For example:
OPCS4 code Z50.2 should map to concept_id 4144227 Standard SNOMED ; This concept_id is pulled via reuse feature from another scan report with the correct concept_id but at the same time an automated concept_id is generated 44516478 Non-Standard OPCS4 concept. **_This shouldn't be happening because automated mapping should always map to standard concept_id._**
Also I was of an impression that Anatomic Site is not implemented yet. The code Z50.2 is from domain Spec Anatomic Site so I am assuming this has been implemented now?

More cases can be seen in screenshot or here -> https://carrot.ac.uk/scanreports/645/tables/3656/fields/141306/
https://carrot.ac.uk/scanreports/645/tables/3656/fields/141306/
I have checked ICD10 codes too but it seems only OPCS4 codes are affected by this bug. 

<img width="766" alt="mapper-5" src="https://github.com/Health-Informatics-UoN/Carrot-Mapper/assets/58890026/eb5bdf1c-fffb-40fd-9cc1-f3216d427b9e">

### Expected Behavior

Map OPCS4 codes to standard concept_id

### Steps To Reproduce

More cases can be seen in screenshot or here ->
https://carrot.ac.uk/scanreports/645/tables/3656/fields/141306/

### Environment

```markdown
- OS:
- Other environment details:
```

### Are you willing to contribute to resolve this issue?

None

**Comment by AndyRae** [comment]
Hi @erummas - we're beginning to look at this bug, but we don't have access to that Scan Report, we can change this in our admin, but wanted to check it was okay with you before we did?

**Comment by erummas** [comment]
Hi @AndyRae yes it’s OK for you to access this SR.
