### ISSUE TITLE
Add a sidebar and brand

### ISSUE THREAD

**Issue by AndyRae** [Health-Informatics-UoN/Carrot-Mapper#808]
Add a sidebar for Carrot

- [ ] Add the component
- [ ] Add configuration (which menu items)
- [ ] Make it collapsible by default
- [ ] Add the brand - "🥕 Carrot"

List of menu items:
- [ ] Datasets
- [ ] Scan Reports
- [ ] Add new Scan Report
- [ ] Documentation

User Menu as a dropdown
- [ ] Username as trigger
- [ ] Change Password link
- [ ] Logout

**Comment by spco** [comment]
Ok to use the logo from https://github.com/Health-Informatics-UoN/carrot-docs/blob/main/docs/images/favicon.png?

**Comment by AndyRae** [comment]
Yes that's the plan :) thanks Sam!

**Comment by AndyRae** [comment]
Also @AndrewThien I'll let you judge whether this is the moment to add dark mode support..

https://ui.shadcn.com/docs/dark-mode/next
