### ISSUE TITLE
Numeric value in the text box changes with up & down and zoom in & out

### ISSUE THREAD

**Issue by erummas** [Health-Informatics-UoN/Carrot-Mapper#816]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In the current(older version) GUI, the concept_id (or any numeric value) increases/decreases with up and down arrow and zoom in and out using the mouse pad. 

### Expected Behavior

The numeric value entered should not change. Mouse pad / up down keys are used very frequently especially with copy pasting and scrolling. 

### Environment

```markdown
- OS:
- Other environment details:
```

### Are you willing to contribute to resolve this issue?

None

**Comment by AndyRae** [comment]
Interestingly @armando-mv was showing us this the other day - given this bit of the UI has not changed in years, I wonder if browser updates have provoked this into an issue.

So yes - this looks annoying, we are really hoping to have the new UI again very very soon, but if we have to keep the legacy UI much longer we will fix this.

**Comment by erummas** [comment]
@AndyRae could be, as I don't remember this happening before.

**Comment by AndyRae** [comment]
We're comfortably using the new UI now, so closing this issue.
