### ISSUE TITLE
Mapper not generating rules in the json file 

### ISSUE THREAD

**Issue by erummas** [Health-Informatics-UoN/Carrot-Mapper#818]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I download the mapping rules for SHARE_SMR01 it just showed 'null' in the json file. Tried to check if this happens with other scan reports but the mapper stopped responding after that.
![image](https://github.com/user-attachments/assets/b317125f-41e2-4506-bd99-850469c42966)

### Expected Behavior

download all the rules in the JSON format

### Environment

```markdown
- OS:
- Other environment details:
```

### Are you willing to contribute to resolve this issue?

None

**Comment by AndyRae** [comment]
I'm not sure if this just happened to be at the moment where all the infrastructure decided to stop working.

But - I have actually observed this on occasions in our test instance (and fixed it). We'll test in depth to see if we can recreate anything, but do let me know if this reoccurs. It's obviously the entire point of the application, so it's very high priority for us.

For reporting - we might not see any errors of it failing in our monitoring, so details on the specific Scan Report ID is helpful.

**Comment by erummas** [comment]
The mapper crashed before I could get the SR ID thus only mentioned the name here is the link to the SR for future reference -> https://carrot.ac.uk/scanreports/669/

**Comment by AndyRae** [comment]
Yes I think the size of the rules files now mean we'll look at moving this to a different way of getting the rules. 
It might have to be a - request the rules file, and we'll let you know when it's ready. It'd be immediate for small size, but this is necessary for the scale we would like to reach. 

Agreed on the JSON structure too - it might have been to compress it and make the file smaller. We'll see what we can do, I don't think it's meant to be human readable but I end up looking through them a lot.

**Comment by erummas** [comment]
Thanks @AndyRae, I make changes in the rules file to include mappings and fields that are currently not available through mapper, much easier to do with the older format.

**Comment by AndyRae** [comment]
@erummas for the meantime, this formatter https://jsonformatter.org seems to cope okay with larger files and formatting. Although it might download back a .txt file that you can rename to .json

**Comment by erummas** [comment]
Thank you @AndyRae, very helpful to know!

**Comment by AndyRae** [comment]
We've been testing the rules generation and there are no errors, just can take a while for large files. So closing this for now.

**Comment by AndyRae** [comment]
@erummas agreed - that doesn't work for me, it downloads a null file.
Interestingly we were testing on a rule set that is twice as big, which it still works for. But none of this is good - we're asking the app to do too much to build these larger rule sets. 

Also I temporarily added myself to view that scan report / dataset / project so I could see the problem, I'll remove myself for now.

**Comment by erummas** [comment]
That's interesting to know, I wonder what is stopping the download process for this one. Thanks for prioritising it @AndyRae

**Comment by erummas** [comment]
Thank you so much @AndyRae and team for fixing this on priority. It's working great so far and I have been able to successfully download rules for sm01. Have a couple more scan reports with similar sized rules so will hopefully test the download on that too later today.
