### ISSUE TITLE
Request to change the naming convention of the rules Mapping JSON file

### ISSUE THREAD

**Issue by erummas** [Health-Informatics-UoN/Carrot-Mapper#822]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your proposal related to a problem or functionality gap?

Currently all files are downloaded with the name 'Mapping JSON' thus unable to distinguish files if you download multiples.

### Describe your proposal

In the old GUI the name of the file was like DataPartner_Scan_Reportname.json. 

### Are you willing to contribute to developing this feature?

None

**Comment by AndyRae** [comment]
Agreed, this is really annoying. We'll fix it.
