### ISSUE TITLE
Fields do not appear in the same order as in source data/SR

### ISSUE THREAD

**Issue by erummas** [Health-Informatics-UoN/Carrot-Mapper#854]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your proposal related to a problem or functionality gap?

The fields are not appearing in the same order as in scan report and by default are ordered alphabetically A-Z. 

### Describe your proposal

Could this be changed back to how it was previously where you could only sort fields when needed via the sorting filter. 

### Are you willing to contribute to developing this feature?

None

**Comment by AndyRae** [comment]
Yep we'll change this back to the default order by id. Should have a release early next week for this.
