### ISSUE TITLE
Unable to upload scan report because of upload restrictions

### ISSUE THREAD

**Issue by erummas** [Health-Informatics-UoN/carrot-mapper#903]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Hi I am getting the following Error on scan report upload
Data partner: Public Health Scotland
Dataset: PHS_SMR01
![Image](https://github.com/user-attachments/assets/15dac64e-6345-4855-8fbb-a04fa4575482)

### Environment

- OS:
- Other environment details:

### Are you willing to contribute to resolve this issue?

None

**Comment by AndyRae** [comment]
Hi @erummas  - I _think_ Carrot might be working as designed here, but I want to check through to confirm.

For the `PHS_SMR01` dataset, you are not an admin or editor, so therefore should not have permission to upload a Scan Report. Only `calum` is an admin of that dataset. You can still see it, as you are attached to the Project `HDR-EPCC-PHS` and it is `public`.

We/Calum can obviously change this, but I want to check that you didn't create the dataset yourself and expect to be an admin? 
It looks like it was created back on March 2024, along with `Deaths` and `PHS_SMR00`. All of them only have `calum` as admin, and he is the only one who has uploaded Scan Reports to them.

**Comment by erummas** [comment]
Got it @AndyRae, thats alright;.
